# H2 para testes
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true

# JWT para testes (chave fixa, mas segura para ambiente de teste)
jwt.secret-key=n8Fv3KxPz7LmQ2rT9wYs6HdJ4uBc1EaZ
jwt.expire-days=0
jwt.expire-hours=0
jwt.expire-minutes=30
