spring.application.name=demo-park-api

## TERMINAL
spring.output.ansi.enabled="ALWAYS"

## LOCALE
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update

# MySQL Database Connection Properties
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT
jwt.secret-key=${JWT_SECRET_KEY}
jwt.expire-days=0
jwt.expire-hours=0
jwt.expire-minutes=30

# Springdoc OpenApi 3.1 & Swagger 3
springdoc.swagger-ui.path=/docs-park.html
springdoc.api-docs.path=/docs-park
springdoc.packagesToScan=com.caiohenrique.demo_park_api.web.controller
